### ISSUE TITLE
无法自动评价

### ISSUE THREAD

**Issue by Inliang** [rootphantomer/jd_AutoComment#6]
脚本无法运行，提示日志如下
![JD](https://github.com/rootphantomer/jd_AutoComment/assets/79506519/b21b01d1-f971-4e32-b697-d26662331558)

**Comment by rootphantomer** [comment]
> 脚本无法运行，提示日志如下 ![JD](https://user-images.githubusercontent.com/79506519/283991079-b21b01d1-f971-4e32-b697-d26662331558.png)

urllib库太久了吧。

**Comment by Inliang** [comment]
> > 脚本无法运行，提示日志如下 ![JD](https://user-images.githubusercontent.com/79506519/283991079-b21b01d1-f971-4e32-b697-d26662331558.png)
> 
> urllib库太旧了吧。pip install urllib3 requests 试试看。

更新后可以使用了，感谢大佬
